"""The three experimental arms.

The question (Decision 12, question F): under what conditions does a bounded
self-improvement loop improve a small language model, and when does it collapse?
Does *accumulating* real and synthetic data, rather than *replacing* real with
synthetic, change the answer?

Every arm is evaluated on the same held-out **real** validation data. That is
the measurement that matters: a collapsing model gets better and better at
predicting its own output while getting worse at predicting reality, and only
the real held-out set can tell the difference.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass

__all__ = ["ARMS", "Accumulate", "Arm", "Control", "Replace"]


@dataclass
class Arm(ABC):
    name: str
    description: str
    needs_generation: bool = True

    @abstractmethod
    def corpus(self, real: list[str], synthetic_history: list[list[str]]) -> list[str]:
        """Training corpus for this generation.

        ``synthetic_history[i]`` is the corpus generated by this arm's own
        generation-*i* model. Arms never share synthetic data — each lineage is
        independent, or the comparison would not be between lineages at all.
        """


class Control(Arm):
    """Never sees synthetic data. The baseline.

    Essential and easy to skip. Without it, a decline across generations could
    just be the noise floor, or a quirk of re-training repeatedly. The control
    shows what "nothing happening" looks like.
    """

    def __init__(self) -> None:
        super().__init__(
            name="control",
            description="real data only, every generation",
            needs_generation=False,
        )

    def corpus(self, real: list[str], synthetic_history: list[list[str]]) -> list[str]:
        return list(real)


class Replace(Arm):
    """Trains only on the previous generation's output.

    The naive self-improvement loop, and the one the collapse literature
    predicts will degrade: each generation's errors and narrowed distribution
    become the next generation's ground truth.
    """

    def __init__(self) -> None:
        super().__init__(name="replace", description="synthetic data only, from generation n-1")

    def corpus(self, real: list[str], synthetic_history: list[list[str]]) -> list[str]:
        if not synthetic_history:
            return list(real)  # generation 0 has no parent to learn from
        return list(synthetic_history[-1])


class Accumulate(Arm):
    """Trains on the real corpus plus every synthetic corpus so far.

    The competing hypothesis: collapse is a consequence of *discarding* the real
    data, not of adding synthetic data. If this arm holds steady while `replace`
    degrades, that is the result.

    Note the confound this introduces and that the analysis must respect: this
    arm sees strictly more training tokens each generation. Some of any advantage
    is data volume rather than data composition, so a matched-token variant is
    the natural follow-up.
    """

    def __init__(self) -> None:
        super().__init__(name="accumulate", description="real + all synthetic so far")

    def corpus(self, real: list[str], synthetic_history: list[list[str]]) -> list[str]:
        combined = list(real)
        for batch in synthetic_history:
            combined.extend(batch)
        return combined


ARMS: dict[str, type[Arm]] = {"control": Control, "replace": Replace, "accumulate": Accumulate}
