"""The three experimental arms.

The question (Decision 12, question F): under what conditions does a bounded
self-improvement loop improve a small language model, and when does it collapse?
Does *accumulating* real and synthetic data, rather than *replacing* real with
synthetic, change the answer?

Every arm is evaluated on the same held-out **real** validation data. That is
the measurement that matters: a collapsing model gets better and better at
predicting its own output while getting worse at predicting reality, and only
the real held-out set can tell the difference.
"""

from __future__ import annotations

import random
from abc import ABC, abstractmethod
from dataclasses import dataclass

__all__ = ["ARMS", "Accumulate", "Arm", "Control", "Replace"]


@dataclass
class Arm(ABC):
    name: str
    description: str
    needs_generation: bool = True

    @abstractmethod
    def corpus(self, real: list[str], synthetic_history: list[list[str]]) -> list[str]:
        """Training corpus for this generation.

        ``synthetic_history[i]`` is the corpus generated by this arm's own
        generation-*i* model. Arms never share synthetic data — each lineage is
        independent, or the comparison would not be between lineages at all.
        """


class Control(Arm):
    """Never sees synthetic data. The baseline.

    Essential and easy to skip. Without it, a decline across generations could
    just be the noise floor, or a quirk of re-training repeatedly. The control
    shows what "nothing happening" looks like.
    """

    def __init__(self) -> None:
        super().__init__(
            name="control",
            description="real data only, every generation",
            needs_generation=False,
        )

    def corpus(self, real: list[str], synthetic_history: list[list[str]]) -> list[str]:
        return list(real)


class Replace(Arm):
    """Trains only on the previous generation's output.

    The naive self-improvement loop, and the one the collapse literature
    predicts will degrade: each generation's errors and narrowed distribution
    become the next generation's ground truth.
    """

    def __init__(self) -> None:
        super().__init__(name="replace", description="synthetic data only, from generation n-1")

    def corpus(self, real: list[str], synthetic_history: list[list[str]]) -> list[str]:
        if not synthetic_history:
            return list(real)  # generation 0 has no parent to learn from
        return list(synthetic_history[-1])


class Accumulate(Arm):
    """Trains on the real corpus plus every synthetic corpus so far.

    The competing hypothesis: collapse is a consequence of *discarding* the real
    data, not of adding synthetic data. If this arm holds steady while `replace`
    degrades, that is the result.

    Note the confound this introduces and that the analysis must respect: this
    arm sees strictly more training tokens each generation. Some of any advantage
    is data volume rather than data composition, so a matched-token variant is
    the natural follow-up.
    """

    def __init__(self) -> None:
        super().__init__(name="accumulate", description="real + all synthetic so far")

    def corpus(self, real: list[str], synthetic_history: list[list[str]]) -> list[str]:
        combined = list(real)
        for batch in synthetic_history:
            combined.extend(batch)
        return combined


class Anchor(Arm):
    """Fixed pool size, configurable real fraction. **Discards real data.**

    The distinction from :class:`Accumulate` is the whole point of this arm.
    `accumulate` never loses any real data — it keeps all 373k real tokens and
    lets the *fraction* fall by piling synthetic data on top. `anchor` holds the
    total pool constant and throws real data away to make room, so at 25% real it
    holds roughly 93k real tokens rather than 373k.

    That separates two claims R8 could not distinguish: whether a lineage needs
    real data to be a certain **share** of what it trains on, or a certain
    **absolute quantity** of it. They have opposite practical consequences for a
    self-improvement loop — under the first, a corpus can grow indefinitely if
    the real share is topped up; under the second, the real corpus is a fixed
    asset and dilution is harmless.

    The real subset is reshuffled per generation from a seeded RNG, so a lineage
    does not spend every generation on the same fixed half of the corpus — that
    would confound "less real data" with "the same real data repeatedly".
    """

    def __init__(self, real_fraction: float = 0.5, seed: int = 0) -> None:
        if not 0.0 <= real_fraction <= 1.0:
            raise ValueError(f"real_fraction must be in [0, 1], got {real_fraction}")
        super().__init__(
            name=f"anchor{real_fraction:g}",
            description=f"fixed pool, {real_fraction:.0%} real data (discards the rest)",
        )
        self.real_fraction = real_fraction
        self.seed = seed

    def corpus(self, real: list[str], synthetic_history: list[list[str]]) -> list[str]:
        if not synthetic_history:
            return list(real)
        synthetic = synthetic_history[-1]

        # Both corpora are generated at matched token counts, so sampling by
        # document count approximates the intended token mix closely enough; the
        # experiment prints the realised counts so the approximation is visible
        # rather than assumed.
        rng = random.Random(self.seed * 1000 + len(synthetic_history))
        n_real = int(len(real) * self.real_fraction)
        n_synthetic = int(len(synthetic) * (1.0 - self.real_fraction))

        chosen_real = rng.sample(real, min(n_real, len(real)))
        chosen_synthetic = rng.sample(synthetic, min(n_synthetic, len(synthetic)))
        return chosen_real + chosen_synthetic


ARMS: dict[str, type[Arm]] = {"control": Control, "replace": Replace, "accumulate": Accumulate}
